version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=reservation
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - '5432:5432'
